### ISSUE TITLE
MTG graphical issue

### ISSUE THREAD

**Issue by FreakHaxme** [FreakHaxme/Game-tracker#7] opened 2019-06-14 03:17 UTC
Graphical issue when doing damage or healing a player

**Comment by martintc** [comment] 2019-06-14 03:24
I believe the issue is to how the setDefaultLokAndFeelDecorated method is called on mainFrame object. Will experiment with this tonight. Also, how the frame is "refreshed." Will experiment with this tonight as the current iteration is a crude implementation.

**Comment by martintc** [comment] 2019-06-15 08:32
Issue with UI changing appearance has been fixed. setDefaultLookAndFeelDecorated removed. Now UI maintains the same appearance. Issue still persists with the movement of the menu.

**Comment by martintc** [comment] 2019-06-15 09:19
Issue for UI changing positions has been solved. Documented in the README and in the commit messages. Closing issue.

**Closed by martintc** 2019-06-15 09:19 UTC
